.TH emerald 1 2006-10-19 Emerald "Emerald"
.SH NAME
emerald - The Emerald Windows Decorator
.SH SYNOPSIS
.B emerald [\-\-replace] [\-\-help] [\-\-version]
.SH DESCRIPTION
.I emerald
emerald is the windows decorator of the beryl project.
\.
.SH OPTIONS
.TP 5
.RI \-\-replace
Replaces a current running decorator
.TP 5
.RI \-\-version
outputs the current version of
.I emerald
.TP 5
\-\-help
short usage statement about
.I emerald
.SH SIGNALS
.TP 5
.RI USR1
Reloads its settings.
.SH FILES
.TP 5
.RI $HOME/.emerald/settings.ini
Here are the settings stored.
.SH AUTHORS
- Quinn Storm (livinglatexkali@gmail.com)
.SH "SEE ALSO"
.BR beryl "(1)
.BR beryl-manager "(1)
.BR emerald-theme-manager "(1)
