.TH emerald-theme-manager 1 2006-10-19 The Emerald Theme Manager "Emerald Theme Manager"
.SH NAME
emerald-theme-manager - The Emerald Theme Manager
.SH SYNOPSIS
.B emerald-theme-manager 
.SH DESCRIPTION
.I emerald-theme-manager
is the theme manager of emerald.
\.
.TP 5
.RI $HOME/.emerald/settings.ini
Here are the settings stored.
.SH AUTHORS
- Quinn Storm (livinglatexkali@gmail.com)
.SH "SEE ALSO"
.BR emerald "(1)
